# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RTCHs5QPZaZvjGYAPxca182etoupCeBo
"""

print("I am signing up for Replit 100 days of Python challenge! I will make sure to spend some time every day coding along, for a minimum of 10 minutes a day. I'll be using Replit, an amazing online IDE so I can do this from my phone wherever I happend to be. No excuses for not coding from the middle of a field!")

my_dictionary={"Trojan,DOS,DDOS,Spyware"}
Trojan="Virus is a type of malware that downloads onto a computer disguised as a legitimate program. "
DOS="A Denial-of-Service (DoS) attack is an attack meant to shut down a machine or network, making it inaccessible to its intended users."
DDOS="DDoS Attack means Distributed Denial-of-Service (DDoS) Attack and it is a cybercrime in which the attacker floods a server with internet traffic to prevent users from accessing connected online services and sites."
Spyware="Spyware is malicious software that enters a user's computer, gathers data from the device and user, and sends it to third parties without their consent."
print(type(my_dictionary))

print("\t\t\tcalculating EB bill")
type=int(input("\n select the residntial palce:\n\n1.household\n2.commercial\n"))
if(type ==1):
  def house():
    print("EB Bill for your House:")
    
    unit=int(input("enter the units:"))
    if(unit<=100):
        ui=unit*0.50
    elif unit>=101 and unit<200:
         ui=unit*0.75
    elif unit<201 and unit<300:
         ui=unit*1.20
    elif unit>300:
         ui=unit*1.50    
    
    print("total charges:",ui)
  house()  
if(type ==2):
     def com():
      print("EB Bill for your Commercial palce:")
   
     unit=int(input("enter the units:"))
     if (unit<=100):
        ui=unit*0.50
     elif unit>=101 and unit<200:
         ui=unit*0.75
     elif unit<201 and unit<300:
         ui=unit*1.20
     elif unit>300:
         ui=unit*1.50    
    
     print("total charges:",ui)
     com()

def personal_details():
    Name = ["Vijay", "Ajith", "Kamal", "Rajini", "Suriya", "Simbu", "vikram", "Jayam Ravi", "Aditya Karikalan", "Vandhiyadevan",]
    Age = ["21", "22", "36", "38", "26", "53", "29", "43", "29", "67",]
    DOB = "27 02 2001"
    Height = "5.1"
    Weight = "62"
    print("Name: {}\nAge: {}\nDOB: {}\nHeight: {}\nWeight: {}".format(Name, Age, DOB, Height, Weight,))

personal_details()

i=(int(input("NUMBER OF STUDENTS:")))
if(i<10):
  name=input("NAME:")
  dob=(input("DATE OF BIRTH:"))
  doy=int(input("DATE OF YEAR:"))
  age=2022-doy
  print("AGE:",age)
  w=int(input("WEIGHT"))
  h=int(input("HEIGHT"))
  bmi=(w/h/h)*10000
  print("BMI:",bmi)
if(bmi<15):
  print("under weight")
elif(bmi<50):
  print("normal")
elif(bmi<100):
  print("----------------over weight--------------")

a=12300
gst=12300*18/100
print(gst)